### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by RuochenLyu** [mycolorway/tao_form#1]
**问题 1**
https://github.com/mycolorway/tao_form/blob/master/lib/assets/stylesheets/tao/form/layout.scss#L139

这里的 `form-without-label` 应该是给 `tao-form` 的吧，因为使用的时候是这样的：

```
<%= tao_form todo, url: url, remote: true, html: {class: 'form-without-label'} do |f| %>
<% end %>
```

这个 class 实际在 `tao-form` 上，而不是 `form`

---

**问题 2**
![image](https://user-images.githubusercontent.com/1207465/27165219-04346de6-51c5-11e7-9a3f-c7df9d1a51b9.png)

**Comment by farthinker** [comment]
已修复
